import { Buffer } from 'node:buffer'
import { z } from 'zod'
import {
  env,
  OPENAI_SPEECH_VOICES,
} from '../../config/env.js'
import { AppError } from '../../errors/AppError.js'
import {
  getOpenAIClient,
} from '../../platform/ai/openaiClient.js'

export const SPEECH_TEXT_MAX_LENGTH = 4096

export const SPEECH_AUDIO_MAX_SIZE_BYTES =
  10 * 1024 * 1024

export const AI_GENERATED_SPEECH_DISCLOSURE =
  'This audio was generated by artificial intelligence using a general synthetic voice. It is not the memory subject’s real or imitated voice.'

const OPENAI_SPEECH_INSTRUCTIONS =
  'Read the input exactly as written. Speak naturally and clearly in the language of the input. Use a calm, respectful tone and a neutral general-purpose synthetic voice. Do not imitate a specific person.'

const speechRequestSchema =
  z.strictObject({
    userId: z
      .string({
        error:
          'User ID must be a string.',
      })
      .trim()
      .min(1, {
        error:
          'User ID must not be empty.',
      }),

    text: z
      .string({
        error:
          'Speech text must be a string.',
      })
      .trim()
      .min(1, {
        error:
          'Speech text must not be empty.',
      })
      .max(
        SPEECH_TEXT_MAX_LENGTH,
        {
          error:
            `Speech text must not exceed ${SPEECH_TEXT_MAX_LENGTH} characters.`,
        },
      ),
  })

const speechConfigurationSchema =
  z.strictObject({
    model: z
      .string({
        error:
          'Speech model must be a string.',
      })
      .trim()
      .min(1, {
        error:
          'Speech model must not be empty.',
      })
      .max(100, {
        error:
          'Speech model must not exceed 100 characters.',
      }),

    voice: z.enum(
      OPENAI_SPEECH_VOICES,
      {
        error:
          'Speech voice is not supported.',
      },
    ),

    timeoutMs: z
      .number({
        error:
          'Speech timeout must be a number.',
      })
      .int({
        error:
          'Speech timeout must be an integer.',
      })
      .min(1000, {
        error:
          'Speech timeout must be at least 1000 milliseconds.',
      })
      .max(120000, {
        error:
          'Speech timeout must not exceed 120000 milliseconds.',
      }),

    maxAudioBytes: z
      .number({
        error:
          'Maximum speech audio size must be a number.',
      })
      .int({
        error:
          'Maximum speech audio size must be an integer.',
      })
      .min(1, {
        error:
          'Maximum speech audio size must be positive.',
      })
      .max(
        SPEECH_AUDIO_MAX_SIZE_BYTES,
        {
          error:
            `Maximum speech audio size must not exceed ${SPEECH_AUDIO_MAX_SIZE_BYTES} bytes.`,
        },
      ),
  })

function createSpeechProviderError() {
  return new AppError(
    'The speech service is temporarily unavailable.',
    {
      statusCode: 502,
      code:
        'AI_SPEECH_PROVIDER_ERROR',
    },
  )
}

function createInvalidSpeechResponseError() {
  return new AppError(
    'The speech service returned invalid audio.',
    {
      statusCode: 502,
      code:
        'AI_SPEECH_INVALID_RESPONSE',
    },
  )
}

function isMp3Audio(audioBuffer) {
  if (
    !Buffer.isBuffer(audioBuffer) ||
    audioBuffer.length < 2
  ) {
    return false
  }

  const hasId3Header =
    audioBuffer.length >= 3 &&
    audioBuffer
      .subarray(0, 3)
      .toString('ascii') === 'ID3'

  const hasMpegFrameHeader =
    audioBuffer[0] === 0xff &&
    (audioBuffer[1] & 0xe0) === 0xe0

  return (
    hasId3Header ||
    hasMpegFrameHeader
  )
}

function discardAudioBuffer(audioBuffer) {
  if (Buffer.isBuffer(audioBuffer)) {
    audioBuffer.fill(0)
  }
}

async function readSpeechResponse(
  response,
  maxAudioBytes,
) {
  if (
    !response ||
    typeof response.arrayBuffer !==
      'function'
  ) {
    throw createInvalidSpeechResponseError()
  }

  let rawAudio

  try {
    rawAudio =
      await response.arrayBuffer()
  } catch {
    throw createSpeechProviderError()
  }

  let audioBuffer

  try {
    audioBuffer = Buffer.from(rawAudio)
  } catch {
    throw createInvalidSpeechResponseError()
  }

  if (
    audioBuffer.length === 0 ||
    audioBuffer.length >
      maxAudioBytes ||
    !isMp3Audio(audioBuffer)
  ) {
    discardAudioBuffer(audioBuffer)
    throw createInvalidSpeechResponseError()
  }

  return audioBuffer
}

export async function generateSpeechAudio(
  input,
  {
    client,
    model = env.openaiSpeechModel,
    voice = env.openaiSpeechVoice,
    timeoutMs =
      env.openaiSpeechTimeoutMs,
    maxAudioBytes =
      SPEECH_AUDIO_MAX_SIZE_BYTES,
  } = {},
) {
  const validatedRequest =
    speechRequestSchema.parse(input)

  const validatedConfiguration =
    speechConfigurationSchema.parse({
      model,
      voice,
      timeoutMs,
      maxAudioBytes,
    })

  const openAIClient =
    client ?? getOpenAIClient()

  let response

  try {
    response =
      await openAIClient.audio
        .speech.create(
          {
            model:
              validatedConfiguration
                .model,
            voice:
              validatedConfiguration
                .voice,
            input:
              validatedRequest.text,
            instructions:
              OPENAI_SPEECH_INSTRUCTIONS,
            response_format: 'mp3',
          },
          {
            timeout:
              validatedConfiguration
                .timeoutMs,
          },
        )
  } catch (error) {
    if (error instanceof AppError) {
      throw error
    }

    throw createSpeechProviderError()
  }

  const audioBuffer =
    await readSpeechResponse(
      response,
      validatedConfiguration
        .maxAudioBytes,
    )

  return {
    audioBuffer,
    byteLength: audioBuffer.length,
    contentType: 'audio/mpeg',
    fileExtension: 'mp3',
    provider: 'openai',
    model:
      validatedConfiguration.model,
    voice:
      validatedConfiguration.voice,
    isAiGenerated: true,
    disclosure:
      AI_GENERATED_SPEECH_DISCLOSURE,
  }
}
