import {
    beforeEach,
    describe,
    expect,
    it,
    vi,
  } from 'vitest'
  import { AppError } from '../src/errors/AppError.js'

  const mocks = vi.hoisted(() => ({
    assertCanChatWithMemory:
      vi.fn(),

    generateSpeechAudio:
      vi.fn(),

    ChatConversation: {
      findOne: vi.fn(),
    },

    ChatMessage: {
      findOne: vi.fn(),
    },
  }))

  vi.mock(
    '../src/modules/memories/memoryAccessService.js',
    () => ({
      assertCanChatWithMemory:
        mocks.assertCanChatWithMemory,
    }),
  )

  vi.mock(
    '../src/modules/voice/openaiSpeechProvider.js',
    async (importOriginal) => {
      const actual =
        await importOriginal()

      return {
        ...actual,
        generateSpeechAudio:
          mocks.generateSpeechAudio,
      }
    },
  )

  vi.mock(
    '../src/modules/chat/ChatConversation.js',
    () => ({
      default:
        mocks.ChatConversation,
    }),
  )

  vi.mock(
    '../src/modules/chat/ChatMessage.js',
    () => ({
      default: mocks.ChatMessage,
    }),
  )

  import {
    generateMemoryChatMessageSpeech,
  } from '../src/modules/voice/speechService.js'

  const userId =
    '507f1f77bcf86cd799439010'

  const memoryId =
    '507f1f77bcf86cd799439011'

  const conversationId =
    '507f1f77bcf86cd799439012'

  const messageId =
    '507f1f77bcf86cd799439013'

  const assistantContent =
    'שרה עבדה כמורה בבית ספר.'

  function createMessageQuery(result) {
    const query = {
      select: vi.fn(),
      lean: vi.fn(),
    }

    query.select.mockReturnValue(query)
    query.lean.mockResolvedValue(result)

    return query
  }

  function createSpeechResult() {
    const audioBuffer =
      Buffer.from([
        0x49,
        0x44,
        0x33,
        0x04,
        0x00,
        0x00,
      ])

    return {
      audioBuffer,
      byteLength: audioBuffer.length,
      contentType: 'audio/mpeg',
      fileExtension: 'mp3',
      provider: 'openai',
      model: 'gpt-4o-mini-tts',
      voice: 'marin',
      isAiGenerated: true,
      disclosure:
        'This audio was generated by artificial intelligence.',
    }
  }

  beforeEach(() => {
    vi.resetAllMocks()

    mocks.assertCanChatWithMemory
      .mockResolvedValue({
        memoryProfile: {
          id: memoryId,
        },
        authorization: {
          role: 'owner',
          permission: 'chat',
          accessType: 'owner',
        },
      })

    mocks.ChatConversation.findOne
      .mockResolvedValue({
        _id: conversationId,
      })

    mocks.ChatMessage.findOne
      .mockReturnValue(
        createMessageQuery({
          _id: messageId,
          content: assistantContent,
        }),
      )

    mocks.generateSpeechAudio
      .mockResolvedValue(
        createSpeechResult(),
      )
  })

  describe('Speech service', () => {
    it('generates speech from an authorized stored assistant message', async () => {
      const result =
        await generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        )

      expect(
        mocks.assertCanChatWithMemory,
      ).toHaveBeenCalledWith(
        userId,
        memoryId,
      )

      expect(
        mocks.ChatConversation.findOne,
      ).toHaveBeenCalledWith({
        _id: conversationId,
        memoryId,
        participantUserId: userId,
        status: 'active',
      })

      expect(
        mocks.ChatMessage.findOne,
      ).toHaveBeenCalledWith({
        _id: messageId,
        conversationId,
        memoryId,
        participantUserId: userId,
        role: 'assistant',
      })

      expect(
        mocks.generateSpeechAudio,
      ).toHaveBeenCalledWith({
        userId,
        text: assistantContent,
      })

      expect(result).toMatchObject({
        contentType: 'audio/mpeg',
        provider: 'openai',
        isAiGenerated: true,
      })

      expect(
        Buffer.isBuffer(
          result.audioBuffer,
        ),
      ).toBe(true)
    })

    it('rejects invalid identifiers before authorization or database access', async () => {
      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          'invalid-message',
        ),
      ).rejects.toMatchObject({
        name: 'ZodError',
      })

      expect(
        mocks.assertCanChatWithMemory,
      ).not.toHaveBeenCalled()

      expect(
        mocks.ChatConversation.findOne,
      ).not.toHaveBeenCalled()

      expect(
        mocks.ChatMessage.findOne,
      ).not.toHaveBeenCalled()
    })

    it('stops before database and OpenAI access when permission is denied', async () => {
      mocks.assertCanChatWithMemory
        .mockRejectedValue(
          new AppError(
            'Memory profile was not found.',
            {
              statusCode: 404,
              code: 'MEMORY_NOT_FOUND',
            },
          ),
        )

      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        ),
      ).rejects.toMatchObject({
        statusCode: 404,
        code: 'MEMORY_NOT_FOUND',
      })

      expect(
        mocks.ChatConversation.findOne,
      ).not.toHaveBeenCalled()

      expect(
        mocks.ChatMessage.findOne,
      ).not.toHaveBeenCalled()

      expect(
        mocks.generateSpeechAudio,
      ).not.toHaveBeenCalled()
    })

    it('returns a safe error when the conversation is unavailable', async () => {
      mocks.ChatConversation.findOne
        .mockResolvedValue(null)

      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        ),
      ).rejects.toMatchObject({
        statusCode: 404,
        code:
          'CHAT_CONVERSATION_NOT_FOUND',
      })

      expect(
        mocks.ChatMessage.findOne,
      ).not.toHaveBeenCalled()

      expect(
        mocks.generateSpeechAudio,
      ).not.toHaveBeenCalled()
    })

    it('returns a safe error for a missing or non-assistant message', async () => {
      mocks.ChatMessage.findOne
        .mockReturnValue(
          createMessageQuery(null),
        )

      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        ),
      ).rejects.toMatchObject({
        statusCode: 404,
        code: 'CHAT_MESSAGE_NOT_FOUND',
      })

      expect(
        mocks.ChatMessage.findOne,
      ).toHaveBeenCalledWith(
        expect.objectContaining({
          role: 'assistant',
        }),
      )

      expect(
        mocks.generateSpeechAudio,
      ).not.toHaveBeenCalled()
    })

    it('rejects an assistant message that exceeds the speech limit', async () => {
      mocks.ChatMessage.findOne
        .mockReturnValue(
          createMessageQuery({
            _id: messageId,
            content:
              'a'.repeat(4097),
          }),
        )

      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        ),
      ).rejects.toMatchObject({
        statusCode: 422,
        code:
          'CHAT_MESSAGE_NOT_SPEAKABLE',
      })

      expect(
        mocks.generateSpeechAudio,
      ).not.toHaveBeenCalled()
    })

    it('preserves a safe OpenAI speech failure', async () => {
      mocks.generateSpeechAudio
        .mockRejectedValue(
          new AppError(
            'The speech service is temporarily unavailable.',
            {
              statusCode: 502,
              code:
                'AI_SPEECH_PROVIDER_ERROR',
            },
          ),
        )

      await expect(
        generateMemoryChatMessageSpeech(
          userId,
          memoryId,
          conversationId,
          messageId,
        ),
      ).rejects.toMatchObject({
        statusCode: 502,
        code:
          'AI_SPEECH_PROVIDER_ERROR',
      })
    })
  })
