import { Buffer } from 'node:buffer'
import request from 'supertest'
import {
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from 'vitest'
import { AppError } from '../src/errors/AppError.js'

const mocks = vi.hoisted(() => ({
  verifyAccessToken: vi.fn(),
  chatSpeechRateLimiter:
    vi.fn(),
  chatRealtimeSpeechChunkRateLimiter:
    vi.fn(),
  generateMemoryChatMessageSpeech:
    vi.fn(),
}))

vi.mock(
  '../src/modules/auth/tokens.js',
  () => ({
    verifyAccessToken:
      mocks.verifyAccessToken,
  }),
)

vi.mock(
  '../src/modules/voice/speechRateLimiter.js',
  () => ({
    chatSpeechRateLimiter:
      mocks.chatSpeechRateLimiter,
    chatRealtimeSpeechChunkRateLimiter:
      mocks.chatRealtimeSpeechChunkRateLimiter,
  }),
)

vi.mock(
  '../src/modules/voice/speechService.js',
  () => ({
    generateMemoryChatMessageSpeech:
      mocks
        .generateMemoryChatMessageSpeech,
  }),
)

import app from '../src/app.js'

const userId =
  '507f1f77bcf86cd799439010'

const memoryId =
  '507f1f77bcf86cd799439011'

const conversationId =
  '507f1f77bcf86cd799439012'

const messageId =
  '507f1f77bcf86cd799439013'

const audioBuffer =
  Buffer.from([
    0x49,
    0x44,
    0x33,
    0x04,
    0x00,
    0x00,
  ])

const authentication = {
  userId,
  systemRole: 'user',
  tokenId: 'token-id',
  expiresAt: new Date(
    Date.now() + 15 * 60 * 1000,
  ),
}

function authenticateRequest() {
  mocks.verifyAccessToken
    .mockResolvedValue(
      authentication,
    )
}

beforeEach(() => {
  vi.resetAllMocks()

  mocks.chatSpeechRateLimiter
    .mockImplementation(
      (_req, _res, next) => {
        next()
      },
    )

  mocks
    .chatRealtimeSpeechChunkRateLimiter
    .mockImplementation(
      (_req, _res, next) => {
        next()
      },
    )

  mocks
    .generateMemoryChatMessageSpeech
    .mockResolvedValue({
      audioBuffer,
      byteLength:
        audioBuffer.length,
      contentType: 'audio/mpeg',
      fileExtension: 'mp3',
      provider: 'openai',
      model:
        'gpt-4o-mini-tts',
      voice: 'marin',
      isAiGenerated: true,
      disclosure:
        'This audio was generated by artificial intelligence.',
    })
})

describe('Speech routes', () => {
  it('returns protected AI-generated MP3 audio for an assistant message', async () => {
    authenticateRequest()

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )
      .buffer(true)
      .parse(
        (res, callback) => {
          const chunks = []

          res.on('data', (chunk) => {
            chunks.push(chunk)
          })

          res.on('end', () => {
            callback(
              null,
              Buffer.concat(chunks),
            )
          })
        },
      )

    expect(response.status).toBe(200)

    expect(
      mocks.chatSpeechRateLimiter,
    ).toHaveBeenCalledTimes(1)

    expect(
      mocks
        .generateMemoryChatMessageSpeech,
    ).toHaveBeenCalledWith(
      userId,
      memoryId,
      conversationId,
      messageId,
    )

    expect(response.headers)
      .toMatchObject({
        'content-type':
          'audio/mpeg',
        'content-length':
          String(audioBuffer.length),
        'content-disposition':
          'inline; filename="memory-response.mp3"',
        'cache-control':
          'private, no-store, max-age=0',
        'x-content-type-options':
          'nosniff',
        'x-ai-generated-audio':
          'true',
      })

    expect(
      Buffer.compare(
        response.body,
        audioBuffer,
      ),
    ).toBe(0)
  })

  it('returns protected MP3 audio for an approved ElevenLabs custom voice', async () => {
    authenticateRequest()

    const mp3Buffer = Buffer.from([
      0x49,
      0x44,
      0x33,
      0x04,
      0x00,
      0x00,
    ])

    mocks
      .generateMemoryChatMessageSpeech
      .mockResolvedValue({
        audioBuffer: mp3Buffer,
        byteLength:
          mp3Buffer.length,
        contentType: 'audio/mpeg',
        fileExtension: 'mp3',
        provider: 'elevenlabs',
        model: 'eleven_v3',
        voice:
          'approved-custom-clone',
        voiceType: 'custom_clone',
        isAiGenerated: true,
        disclosure:
          'AI custom voice.',
      })

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )
      .buffer(true)
      .parse(
        (res, callback) => {
          const chunks = []

          res.on('data', (chunk) => {
            chunks.push(chunk)
          })

          res.on('end', () => {
            callback(
              null,
              Buffer.concat(chunks),
            )
          })
        },
      )

    expect(response.status).toBe(200)
    expect(response.headers)
      .toMatchObject({
        'content-type': 'audio/mpeg',
        'content-disposition':
          'inline; filename="memory-response.mp3"',
        'x-ai-generated-audio':
          'true',
        'x-ai-voice-type':
          'custom_clone',
      })

    expect(
      Buffer.compare(
        response.body,
        mp3Buffer,
      ),
    ).toBe(0)
  })

  it('requires authentication before speech generation', async () => {
    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )

    expect(response.status).toBe(401)

    expect(
      mocks.chatSpeechRateLimiter,
    ).not.toHaveBeenCalled()

    expect(
      mocks
        .generateMemoryChatMessageSpeech,
    ).not.toHaveBeenCalled()
  })

  it('rejects invalid speech route identifiers', async () => {
    authenticateRequest()

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/invalid-message/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )

    expect(response.status).toBe(400)

    expect(response.body.error)
      .toMatchObject({
        code: 'VALIDATION_ERROR',
        message:
          'Request validation failed.',
        requestId: expect.any(String),
      })

    expect(
      mocks.chatSpeechRateLimiter,
    ).not.toHaveBeenCalled()

    expect(
      mocks
        .generateMemoryChatMessageSpeech,
    ).not.toHaveBeenCalled()
  })

  it('returns a safe response when access or the message is unavailable', async () => {
    authenticateRequest()

    mocks
      .generateMemoryChatMessageSpeech
      .mockRejectedValue(
        new AppError(
          'Chat message was not found.',
          {
            statusCode: 404,
            code:
              'CHAT_MESSAGE_NOT_FOUND',
          },
        ),
      )

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )

    expect(response.status).toBe(404)

    expect(response.body.error)
      .toMatchObject({
        code:
          'CHAT_MESSAGE_NOT_FOUND',
        message:
          'Chat message was not found.',
        requestId: expect.any(String),
      })
  })

  it('returns a safe response when OpenAI speech generation fails', async () => {
    authenticateRequest()

    mocks
      .generateMemoryChatMessageSpeech
      .mockRejectedValue(
        new AppError(
          'The speech service is temporarily unavailable.',
          {
            statusCode: 502,
            code:
              'AI_SPEECH_PROVIDER_ERROR',
          },
        ),
      )

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )

    expect(response.status).toBe(502)

    expect(response.body.error)
      .toMatchObject({
        code:
          'AI_SPEECH_PROVIDER_ERROR',
        message:
          'The speech service is temporarily unavailable.',
        requestId: expect.any(String),
      })
  })

  it('returns a safe response when the speech quota is exhausted', async () => {
    authenticateRequest()

    mocks.chatSpeechRateLimiter
      .mockImplementation(
        (_req, _res, next) => {
          next(
            new AppError(
              'Too many speech requests. Please try again shortly.',
              {
                statusCode: 429,
                code:
                  'AI_SPEECH_RATE_LIMITED',
              },
            ),
          )
        },
      )

    const response = await request(app)
      .post(
        `/api/memories/${memoryId}/chat/conversations/${conversationId}/messages/${messageId}/speech`,
      )
      .set(
        'Authorization',
        'Bearer valid-access-token',
      )

    expect(response.status).toBe(429)

    expect(response.body.error)
      .toMatchObject({
        code:
          'AI_SPEECH_RATE_LIMITED',
        message:
          'Too many speech requests. Please try again shortly.',
        requestId: expect.any(String),
      })

    expect(
      mocks
        .generateMemoryChatMessageSpeech,
    ).not.toHaveBeenCalled()
  })
})
